name: Deploy Cloud Functions

on:
  push:
    branches:
      - main # You can adjust this to your preferred branch

jobs:
  deploy:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Set up Python
      # uses: actions/setup-python@v2
      # with:
        # python-version: 3.11

    # - name: Install dependencies
      # run: pip install -r requirements.txt

    - id: oidc
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: id_token
        create_credentials_file: true
        workload_identity_provider: 'projects/490090145490/locations/global/workloadIdentityPools/colgate-pool/providers/colgate-provider'
        service_account: 'github-actions-deployer@nifty-kayak-401516.iam.gserviceaccount.com'

    - name: Deploy Cloud Functions
      run: |
        gcloud functions deploy hello-world \
          --runtime python311 \
          --trigger-http \
          --region us-central1 \
          --entry-point hello_http \
          --allow-unauthenticated # Modify this based on your function configuration
        gcloud functions add-iam-policy-binding hello-world \
          --member "serviceAccount:github-actions-deployer@nifty-kayak-401516.iam.gserviceaccount.com" \
          --role "roles/cloudfunctions.invoker"
