name: Deploy Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Use the version you need

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy hello-world \
            --runtime python311 \
            --trigger-http \
            --entry-point hello_http
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1